### ISSUE TITLE
[Explorer Bug]one transaction displayed twice

### ISSUE THREAD

**Issue by Brochao** [HNScan/HNScan#271]
In one transaction, if an address is both input and output,
the transaction will be displayed twice when query address' information.

*Example*
1.  [hs1qvmxvgm93n6gz2qlmfu3ryj9ta6vku78gpkk22l](https://hnscan.com/address/hs1qvmxvgm93n6gz2qlmfu3ryj9ta6vku78gpkk22l)
2. As you can see, TX 
ba43fc8e533f7a1235f90f95abaf7a2d55e0c808bd220d708f2eab363a533d5a 
is displayed twice.

**Comment by kilpatty** [comment]
Ah thanks for this! I will make sure we fix this asap.

**Comment by kilpatty** [comment]
This is fixed as of our 2.0 release. Thanks again :)
